spring:
 datasource:
        url: jdbc:h2:mem:salasdereuniao_db
        driverClassName: org.h2.Driver
        username: sa
        password:
        
 jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   generate-ddl: true
   hibernate.ddl-auto: update
   show-sql: true


 h2:
  console:
     enabled: true
     path: /h2-console

